version: '3.8'

services:
  db:
    image: postgres:13.7
    container_name: postgres_db 
    restart: always
    env_file:
      - ./.env
    ports:
    - '5432:5432'
    volumes:
    - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db: